### ISSUE TITLE
lots of similar projects and duplicate effort on npm

### ISSUE THREAD

**Issue by graingert** [ragingwind/got-google-fonts#1]
https://npmcompare.com/compare/google-font-installer,google-fonts-downloader,google-fonts-manager,google-fonts-offline,got-google-fonts

**Comment by graingert** [comment]
Here is the issue on multiple projects:

https://github.com/lordgiotto/google-font-installer/issues/6
https://github.com/alberto-bottarini/google-fonts-downloader/issues/4
https://github.com/bali182/google-fonts-manager/issues/1
https://github.com/makovich/google-fonts-offline/issues/4
https://github.com/ragingwind/got-google-fonts/issues/1

**Comment by ragingwind** [comment]
@graingert not same. final goal is same but API interfaces and approaching the problem in the way is different, and it should be respected. For example, this package support export promise API not CLI download only. You only compared the numbers of out of side of project. not deeply.

**Comment by graingert** [comment]
I don't understand what you mean by "You only compared the numbers of out
of side of project. not deeply."
